# Generated by Django 5.2.17 on 2026-09-14 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=7, unique=True)),
                ('meta_pct', models.PositiveSmallIntegerField(default=10)),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('gasto', 'Gasto')], max_length=7)),
                ('descricao', models.CharField(max_length=120)),
                ('categoria', models.CharField(max_length=40)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('fixo', models.BooleanField(default=False)),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='financas.mes')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
